Articles/urls.py
from django.urls import path
from . import views

app_name='articles'
urlpatterns = [
    path('', views.articles_list,name="list"),
    path('<slug>', views.articles_detail,name="detail"),
]

MyDjangoWeblog/urls.py
from django.contrib import admin
from django.urls import path , include
from . import views

urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('Articles/',include('Articles.urls'))
]

Articles/models.py
from django.db import models


# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50]+" ..."

Articles/views.py
from django.shortcuts import render,HttpResponse
from . import models


# Create your views here.
def articles_list(requset):
    articles = models.Article.objects.all().order_by('date')
    args = {'articles': articles}
    return render(requset, "articles/articles_list.html", args)

def articles_detail(requset,slug):
    return HttpResponse(slug)

MyDjangoWeblog/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse


def home(requset):
    return render(requset, "home.html")


def about(requset):
    return render(requset, "about.html")

Articles/templates/articles/articles_list.html
{% extends 'base.html' %}
{% block title %}
    Articles
{% endblock %}

{% block content %}
<div class="container">
<h1>article lists</h1>
{% for article in articles %}
    <h2>
    <a href="{% url 'articles:detail' slug=article.slug  %}">{{ article.title }}</a>
    <p>
        {{ article.snippet }}
    </p>
    <p>
        {{ article.date }}
    </p>
    </h2>
{% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>about</title>
</head>
<body>
<p>
    سلام.
</p>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'styles.css' %}">

    <title>
        {% block title %}
        Articles
        {% endblock %}
    </title>
</head>
<body>
<h2><a href={% url 'articles:list' %}></a></h2>
<div class="wrapper">
    {% block content %}
{% endblock %}
</div>
</body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>خانه</title>
</head>
<body>
<p>
    من محمد حسینو دوست دارم
</p>
</body>
</html>